### ISSUE TITLE
Having the directory arg be --folder or dir is confusing, add --dir support

### ISSUE THREAD

**Issue by martindemello** [fsprojects/Forge#101]
It took me reading the source code to realise that `--folder [dir]` meant the alternate syntaxes were
````
forge --folder <dir>
````
and
````
forge dir <dir>
````

rather than `forge --dir <dir>`. In the interests of least surprise, please add `--dir` as a supported syntax too.

**Comment by spencerwi** [comment]
This is small enough I can actually do it! Should `--folder` remain and `--dir` just be an alias, or should `--folder` _become_ `--dir`?
