### ISSUE TITLE
Using an invalid exception throws an unhandled exception

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/Forge#103]
That causes the error message with the help to take a couple of seconds to appear. Would be nicer if the ArgumentException was caught and the help was just displayed, without showing the stacktrace

**Comment by ovatsus** [comment]
Reproes when doing "forge new"

**Comment by Krzysztof-Cieslak** [comment]
`alpha009` provides bit better way of handling errors

**Comment by ovatsus** [comment]
Thanks, just tested it, and it doesn't pop up WinDBG anymore, which is good :)
