### ISSUE TITLE
Better documentation of "forge new": clarify that it expects to be in the project directory

### ISSUE THREAD

**Issue by rmunn** [fsprojects/Forge#105]
I was subconsciously expecting `forge new` to act a bit like `git clone`, creating a new folder under my current folder and putting the new project there. However, it actually acts more like `git init`, working in the current directory, and this surprised me.

I have a folder on my Windows development machine called `C:\src\learn` where I keep all my "toy" projects: the ones that are just for playing around with various libraries and tools (Eto, Forge, Suave...). When I tried to create a new project just now, this is what happened:

```
C:\src\learn>forge new
Getting templates...
Creating C:\Users\Robin\AppData\Local\scoop\apps\forge\0.7.0\templates
C:\Program Files\Git\cmd\git.exe clone -b templates --single-branch https://github.com/fsprojects/generator-fsharp.git templates

Enter project name:
> TryForge
Enter project directory (relative to working directory):
> TryForge
Choose a template:
 - aspwebapi2
 - classlib
 - console
 - fslabbasic
 - fslabjournal
 - pcl259
 - servicefabrichost
 - servicefabricsuavestateless
 - sln
 - suave
 - suaveazurebootstrapper
 - websharperserverclient
 - websharperspa
 - websharpersuave
 - windows

> console
Generating project...
Creating C:\src\learn\TryForge\TryForge
C:\Users\Robin\AppData\Local\scoop\apps\forge\0.7.0\bin\..\templates\console\App.config => C:\src\learn\TryForge\TryForge\App.config
C:\Users\Robin\AppData\Local\scoop\apps\forge\0.7.0\bin\..\templates\console\ApplicationName.fs => C:\src\learn\TryForge\TryForge\ApplicationName.fs
C:\Users\Robin\AppData\Local\scoop\apps\forge\0.7.0\bin\..\templates\console\ApplicationName.fsproj => C:\src\learn\TryForge\TryForge\ApplicationName.fsproj
C:\src\learn\.paket\paket.exe convert-from-nuget -f
Paket version 2.52.1.0
Dependencies files saved to C:\src\learn\paket.dependencies
Solution C:\src\learn\EtoApp1\EtoApp1.sln changed
Solution C:\src\learn\suave\Todo\Todo\Todo.sln changed
Resolving packages for group Main:
Locked version resolution written to C:\src\learn\paket.lock
2 seconds - ready.
C:\src\learn\.paket\paket.exe add nuget FAKE
Paket version 2.52.1.0
Adding FAKE to C:\src\learn\paket.dependencies into group Main
Resolving packages for group Main:
 - FAKE 4.27.0
Locked version resolution written to C:\src\learn\paket.lock
Dependencies files saved to C:\src\learn\paket.dependencies
Downloading FAKE 4.27.0
15 seconds - ready.
Done!
```

Note especially the two lines:

```
Solution C:\src\learn\EtoApp1\EtoApp1.sln changed
Solution C:\src\learn\suave\Todo\Todo\Todo.sln changed
```

What I was expecting was to see the `paket.dependencies` and `paket.lock` files created in `C:\src\learn\TryForge`. Instead, those files (and the `build.*` files) were created in `C:\src\learn`, and solution files in two *unrelated* projects (`EtoApp1` and `suave\Todo`) were modified to add the `C:\src\learn\paket.dependencies` file to the solution.

Thankfully, the amount of work to undo my mistake is going to be quite small since there were very few projects in `C:\src\learn` -- but if I'd run Forge in my `C:\src` folder instead, it could have been a minor disaster. To avoid that happening to anyone else, it would be nice if the documentation were more clear on how to run `forge new`: **first** create a new folder and `cd` into it, and **then** run `forge new` inside the empty folder.

**Comment by 7sharp9** [comment]
Yeah this is a pretty nasty bug, if your not in a sub dir then the following command get run on everything in that folder:

```
/Library/Frameworks/Mono.framework/Commands/mono  /Users/dave/code/.paket/paket.exe convert-from-nuget -f
Paket version 2.52.1.0
```

**Comment by Krzysztof-Cieslak** [comment]
In latest pre-release I've added big warning at start of Forge and prompt for user, that should be it for now.
