### ISSUE TITLE
Paket file links lose Paket tag on modification

### ISSUE THREAD

**Issue by neoeinstein** [fsprojects/Forge#112]
When Forge makes modifications to an `fsproj` that contains Paket-managed links to file references, the Paket tag is dropped. This causes Paket to re-include the file on the next `paket install`, and results in a build failure.

## Expected Behavior
While Forge may collect the file includes, it should not change the child tags on those items.

## Current Behavior
Forge fails to move the Paket tag when it rewrites file includes.

## Steps to Reproduce
To reproduce, create an F# project, and use `paket add github neoeinstein/YoLo YoLo.fs project myproj.fsproj`. Then make a modification to the project file using Forge. Note that the paket-included file has dropped the `<Paket>True </Paket>` tag.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `alpha009`
