### ISSUE TITLE
"forge paket update" should be valid syntax

### ISSUE THREAD

**Issue by rmunn** [fsprojects/Forge#113]
If I'm using Forge to manage Paket and FAKE, I'll sometimes want to run `paket update`. But running `forge paket update` produces an error:

> System.ArgumentException: argument 'update' should precede all other arguments.

It seems that Forge thinks I'm trying to run `forge update paket` and mistyping it, but I'm actually trying to run `paket update` and I typed my command correctly. This particular ArgumentException is over-enthusiastic.

Suggested fix: when `paket` or `fake` is the first command, further argument parsing should be handed over to those programs rather than having Forge parse the command line further.

**Comment by Krzysztof-Cieslak** [comment]
This got fixed and should work as expected (`forge paket` and `forge fake` passes arguments too Paket and FAKE)
