### ISSUE TITLE
forge file add ../Client.all.fsharp/VoicemailUi.fs; forge file add ../Client.all.fsharp/VoicemailUi.fs adds two references to the file

### ISSUE THREAD

**Issue by banshee** [fsprojects/Forge#116]
run:

    forge file add ../Client.all.fsharp/VoicemailUi.fs; forge file add ../Client.all.fsharp/VoicemailUi.fs

The first one does the expected thing.  The second command reports an error:

    /Users/james/svox_workspace/dev/Client.all.fsharp/VoicemailUi.fs already exists.

However, it adds two lines to the fsproj file:

```
+    <Compile Include="../Client.all.fsharp/VoicemailUi.fs" />
+    <Compile Include="../Client.all.fsharp/VoicemailUi.fs" />
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `alpha010`
