### ISSUE TITLE
"<filename> already exists" diagnostic message is unclear

### ISSUE THREAD

**Issue by banshee** [fsprojects/Forge#117]
If you try to add an existing file to a project using something like

    forge file add ../Client.all.fsharp/VoicemailUi.fs

You'll get a message:

    /Users/james/svox_workspace/dev/Client.all.fsharp/VoicemailUi.fs already exists.

It can exist in two places, though - on disk and in the project file.  It's unclear which one this message is referring to.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `alpha010`
