### ISSUE TITLE
`forge add project` ends up with error `Unrecognized command or missing required parameter` 

### ISSUE THREAD

**Issue by mobius-eng** [fsprojects/Forge#119]
## Summary

Adding the reference to the existing project (`forge add project -n path\to\referenced.fsproj -p \path\to\referencing.fsproj`) finishes with the message

```
Unrecognized command or missing required parameter
```

## Expected Behavior
The reference to referenced project added to referencing project file.

## Current Behavior
No changes in project files. Message "Unrecognized command or missing required parameter"

## Context
Need to reference main project in test project.

## Your Environment
* Windows 10
* Installed via VSCode

**Comment by sradevel** [comment]
Same for `forge new project` on my Windows Box. On Linux everything works as expected.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `alpha009`
