### ISSUE TITLE
Removing project references not working

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Forge#125]
Detected by our new set of tests

https://travis-ci.org/fsprojects/Forge/builds/149209940
https://ci.appveyor.com/project/reidev275/forge/build/0.0.1.266

**Comment by ErikSchierboom** [comment]
I'm also on this :)

**Comment by Krzysztof-Cieslak** [comment]
Fix released in `1.0.0-alpha011`
