### ISSUE TITLE
Be more tolerant with invalid input

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/Forge#129]
## Expected Behavior
When entering a command/name that Forge does not understand, it should not simply exit, but offer retrying or exiting at the user's choice.

## Current Behavior
When mistyping a template name, Forge simply reports "Wrong template name" and exits, so I have to restart the whole process and get to that point again. I think I've seen similar behavior in another place too.

## Possible Solution
Implement a general retry/abort loop to use for all input.

## Your Environment
* Version used: Forge 0.7.0

**Comment by Krzysztof-Cieslak** [comment]
I'm pretty sure it's fixed in `1.0.0-alpha`.  Actually, it's probably better version to use than `0.7.0` ;). So feel free to check it out (you can download compiled version of latest alpha in github releases)
