### ISSUE TITLE
FsLab Journal Template

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Forge#134]
[packages.config](https://github.com/fsprojects/Forge/blob/templates/fslabjournal/packages.config) contains
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FsLab" version="0.2.7" targetFramework="net45" />
  <package id="FsLab.Runner" version="0.2.7" targetFramework="net45" />
  <package id="Suave" version="0.28.1" targetFramework="net45" />
  <package id="FAKE" version="3.34.7" targetFramework="net45" />
</packages>
```

This explicit versioning is bad, an alternative should be used

**Comment by Krzysztof-Cieslak** [comment]
This file was not used anyway, `paket.references` is used instead. It was there by accident (I haven't removed it when porting from old yeoman templates)
