### ISSUE TITLE
Allow 'file add' from the top level directory

### ISSUE THREAD

**Issue by TomMD** [fsprojects/Forge#143]
Given a directory structure of `toplevel/project-dir/{source and project-name.fsproj}` it should be possible to add files when in the toplevel directory.  For example:

```
forge new --name foo --dir src --template console
forge file add src/foo/helper.fs
```

And the result would be the `src/project-name.fsproj` would be augmented.

EDIT:

Recognizing the possibility of multi-project repositories perhaps the syntax would be more like:

```
forge project foo file add x.fs
```

The 'project' statement would disambiguate the project using syntax matching the paket sub-command.  The order of `project` first then `file` avoids issues with adding files named `project` and can still play friendly with multiple file additions (#144).

**Comment by Krzysztof-Cieslak** [comment]
This is fixed in alpha version - https://github.com/fsprojects/Forge/releases
