### ISSUE TITLE
Include a command for adding dependencies

### ISSUE THREAD

**Issue by TomMD** [fsprojects/Forge#145]
Instead of forcing calling out to paket et al, consider a command that wraps up this capability:

```
forge dependency add MathNet.Numerics
```

Currently it appears the requirement is paket:

```
mono .paket/paket.exe add nuget MathNet.Numerics
```

EDIT: Or at least in the help include:

```
forge paket add nuget <pkg> project <proj>

**Comment by Krzysztof-Cieslak** [comment]
This is handled (as You've noticed) by `forge paket` command. To be fair, I don't want to duplicate whole Paket help and documentation here, I guess link to the Paket website should be good enough
