### ISSUE TITLE
Package as NuGet package

### ISSUE THREAD

**Issue by ErikSchierboom** [fsprojects/Forge#147]
It would very convenient if Forge would also be provided as a NuGet package, with `forge.exe` already built. This would make it easier to include Forge as a dependency of a build script.

**Comment by cloudRoutine** [comment]
eventually forge and forge,core will have nuget packages, but i want the project to be at a much higher level of stability first.

**Comment by ErikSchierboom** [comment]
Okay, thanks for explaining!
