### ISSUE TITLE
Default .gitignore file in templates is missing "build" directory

### ISSUE THREAD

**Issue by rmunn** [fsprojects/Forge#151]
The default `.gitignore` file is great, but it's missing a `build/` entry. The "Build Results" section does include an ignore for directories called `bld/`, as well as lots of other possibilities like `debug/` and `Debug/`, `bin/` and `Bin/`, and so on. But `build/` isn't there, potentially causing problems. If you create a new project from Ionide in VS Code, and choose the Console template, the default `build.fsx` file this produces is configured to put its output in `build/` -- so unless you're careful with Git, you'll end up checking in build results that shouldn't have been checked in.

## Expected Behavior
A `build/` entry should be added to `.gitignore`, just below `bld/`.

## Current Behavior
Build output located in `build/` is not ignored, and you might add them to Git by accident while trying to add all files for your initial commit in a new repo.

## Your Environment
VS Code 1.4.0, with Ionide-fsharp 2.4.2, on Linux. Brand-new project created by running the `F#: New Project` command.

**Comment by rmunn** [comment]
This might be better reported as an issue against https://github.com/joeblau/gitignore.io; I'll look into it.

**Comment by rmunn** [comment]
Same issue reported at https://github.com/joeblau/gitignore.io/issues/234; if that one gets fixed, this issue will become a duplicate and could then be closed.

**Comment by Krzysztof-Cieslak** [comment]
Added `build/` entry to default gitignore
