### ISSUE TITLE
File templates?

### ISSUE THREAD

**Issue by SabotageAndi** [fsprojects/Forge#19]
I would like to include file templates in fix.
E.g.: 
fs- File
fxx- File
app/web.config

As the project templates are in the generator-fsharp/templates, should be the file templates than also there?

**Comment by Krzysztof-Cieslak** [comment]
Probably, we should add `.files` folder to generator-fsharp/templates and use them. It's just matter of defining tags which would be used in files.

**Comment by SabotageAndi** [comment]
Has the folder to beginn with a dot? I am on Mac OS X and then the stuff is hidden.
So is simple files or fileTemplates also good?

As tags I was thinking about:
* <%= namespace %> - taken from the project file
* <%= filename %> - name of new file

Any additional ideas for tags?

**Comment by reidev275** [comment]
Don't know that it has to start with a '.' But we do need some way to distinguish those from project templates. 
There's also https://github.com/fsprojects/Fix/blob/master/src/Fix/Templates.fs which may have to change depending upon your approach.

**Comment by SabotageAndi** [comment]
I will think about a solution. Thanks for the hint about Templates.fs.
Hopefully I have some time on the weekend to work on it.

**Comment by Krzysztof-Cieslak** [comment]
Part of #39

**Comment by Krzysztof-Cieslak** [comment]
Part of #49
