### ISSUE TITLE
"fix new xyz" as synonym for "fix new --template xyz"

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/Forge#36]
I'm thinking it would make sense to be able to say eg `fix new classlib`.

**Comment by Krzysztof-Cieslak** [comment]
Maybe `fix new -t classlib` ?

**Comment by Tarmil** [comment]
Yeah I guess that's good too. Most such arguments could benefit from a short form, eg:

    forge new -t classlib -n MyLibrary -d src

**Comment by Tarmil** [comment]
Although `-n` would conflict with the `-n` alias for `new`. Any suggestions?
