### ISSUE TITLE
forge file: manage file item type

### ISSUE THREAD

**Issue by Tarmil** [fsprojects/Forge#42]
It would be useful to manage file item types (Compile, Content, EmbeddedResource, etc).

Minimal support would be a command like `forge file type compile Foo.fs` to modify the type of a file that is already in the project (and fail if it's not there).

It would also be nice to be able to set the item type directly on `forge file add`. Unfortunately Argu doesn't allow passing an optional argument to a named parameter, so we can't allow both `forge file add Foo.fs` and `forge file add compile Foo.fs`. So maybe instead the syntax for both `type` and `add` (for consistency) could be something like `Foo.fs:compile`, with the `:compile` part being optional for `add` with the current defaults.

**Comment by reidev275** [comment]
Initially I was hoping to insulate the user from ever having to know that stuff as it's only necessary because of the fsproj file.  Having it as an optional argument seems like a good compromise.
