### ISSUE TITLE
brew installed Forge 0.6.0 fails with "parameter reserved for 'usage' parameter"

### ISSUE THREAD

**Issue by caindy** [fsprojects/Forge#50]
When I install via homebrew per readme instructions I get [this Argu error](https://github.com/fsprojects/Argu/blob/62f89e837c6ffe98660eaac083932866e9b95eda/src/Argu/ArgInfo.fs#L248)

Cloning this repo and running the build .exe with mono works on my machine.

**Comment by leafgarland** [comment]
I see the same problem. I guess it has been fixed by [this commit](https://github.com/fsprojects/Forge/commit/4c46b841cb1331484a4c04c4acaf8b3719406b4a), which is not in any release yet.

**Comment by mavnn** [comment]
This is where a voting button would be useful; me too on this one.

**Comment by Krzysztof-Cieslak** [comment]
Waiting for https://github.com/samritchie/homebrew-forge/pull/2 to be merged
