### ISSUE TITLE
Should http://fsprojects.github.io/Fix redirect to Forge?

### ISSUE THREAD

**Issue by rmunn** [fsprojects/Forge#60]
I don't know if it's possible to add this redirect without creating a new http://github.com/fsharp/Fix project (which would probably break the http://github.com/fsharp/Fix -> http://github.com/fsharp/Forge redirection). But it might be a good idea to make http://fsprojects.github.io/Fix redirect to http://fsprojects.github.io/Forge, since there may be links to http://fsprojects.github.io/Fix floating around out there on the Internet that will look broken.

If it's only possible to redirect one, but not both, of http://fsprojects.github.io/Fix and http://github.com/fsharp/Fix, then we should at least have the discussion about which redirect is more valuable.

**Comment by Krzysztof-Cieslak** [comment]
As far as I know that's not possible without breaking existing redirection.
