### ISSUE TITLE
Add rename project

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Forge#64]
Adds command for renaming project. Command `rename project` should be implemented. 
## Expected Behavior

- change `.fsproj` file name,
- change `RootNamespace` (if previous one was same as old project name), 
- change `AssemblyName` (if previous one was same as old project name),  
- change `DocumentationFile` (if previous one was same as old project name),
- update references in whole solution. 

## Implementation suggestions
All operations should be implemented using `Forge.ProjectSystem` module
Implementation should be placed in `Forge.ProjectManager` module

**Comment by andredublin** [comment]
I'd like to take this issue on :)

**Comment by andredublin** [comment]
Question about the ConfigSettings since DocumentationFile reside in the object.  FsProject holds a list of ConfigSettings, would I have to rename all DocumentationFile properties in the list of config files of the FsProject type?

**Comment by andredublin** [comment]
Clarified from chat with @cloudRoutine in gitter chat room
> cloudRoutine 21:41
@andredublin What I meant earlier is I made a mistake putting it there and it should be in the other record instead

> andredublin 21:41
Ah
And we're expecting that to be a 0..1 property not a 1..n list right?

> cloudRoutine 21:43
Property<string>
