### ISSUE TITLE
Add list GAC

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Forge#66]
Adds command to list GAC assemblies. `list gac` command should be implemented

## Expected Behavior
Returns list of assemblies in GAC

## Implementation suggestion
GAC functions are implemented in `Forge.GacSearch` module

**Comment by jwood803** [comment]
If it's cool, I'll attempt this. If y'all don't mind that it may take a couple of weeks, of course.

**Comment by jwood803** [comment]
This cool to be closed or waiting to be able to filter the list?
