### ISSUE TITLE
Extend list command with filtering / searching

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Forge#68]
All filtering / searching capabilities to all `list` commands. Add `--filter` parameter to all `list` commands`

## Expected Behavior
Returns only those elements which matches filter query ( match based on string distance) 

## Implementation suggestion
Following string distance implementation can be used - https://github.com/ionide/ionide-fsharp/blob/develop/src/Components/CompletionHelpers.fs#L73-L87

**Comment by spencerwi** [comment]
This seems simple enough that even I could do it.

**Comment by spencerwi** [comment]
I see in existing code this:

```fsharp
type ListFilters =
    | Filter of string
    | Count of int

    interface IArgParserTemplate with
        member this.Usage =
            match this with
            | Filter _ -> "Filter list via fuzzy search for this string"
            | Count _ -> "Return the x best search results"
```

I could add `--filter-name` and `--filter-count` or `--filter` and `--count`, but I think `--filter` on its own works best, allowing users to pipe it into `head` or something equivalent.
