### ISSUE TITLE
Adding reference seems to not work as expected

### ISSUE THREAD

**Issue by rikonor** [fsprojects/Forge#74]
After creating a new console project, I added FSharp.Data to paket.dependencies and had it install the package.

In order to have access to the package in my .fs files, I ran `reference add ../packages/FSharp.Data/lib/net40/FSharp.Data.dll`.

However this created a line:
```<None Include="../packages/FSharp.Data/lib/net40/FSharp.Data.dll" />```

where it should have actually created a line:
```<Reference Include="../packages/FSharp.Data/lib/net40/FSharp.Data.dll" />```

After editing that line by hand to say `Reference` instead of `None`, I was able to use the package in my code.

**Comment by rikonor** [comment]
After further investigation I found it's possible to use paket directly to add the required reference - so I will do it that way for now.
Am I understanding correctly, though, that `forge reference add` should have a similar effect?

**Comment by cloudRoutine** [comment]
referencing out of date version of Forge

**Comment by royalstream** [comment]
FYI, I get the same behavior described by @rikonor and I'm using version 0.7
