### ISSUE TITLE
forge paket requires all additional arguments to be quoted

### ISSUE THREAD

**Issue by reidev275** [fsprojects/Forge#84]
## Expected Behavior
would like to be able to issue `forge paket add nuget FAKE`

## Current Behavior
Currently that errors with `argument 'add' should precede all other arguments`.  Workaround is to issue `forge paket "add nuget FAKE"`

## Implementation suggestion
Looks to be something with the Argu configuration and possibly in https://github.com/fsprojects/Forge/blob/master/src/Forge/Commands.fs

**Comment by domartynov** [comment]
Are you sure? In 1.0.0-alpha008 ``forge paket add nuget FAKE`` seems to work.

**Comment by Krzysztof-Cieslak** [comment]
I think I've fixed it by accident, fixing other bug... maybe ;)
