### ISSUE TITLE
Add .gitignore file when creating new project

### ISSUE THREAD

**Issue by rikonor** [fsprojects/Forge#91]
Is this something you would be willing to consider?
E.g. exclude packages, .paket, etc.

**Comment by xavierzwirtz** [comment]
.hgignore would be handy as well, for the mercurial weenies.

**Comment by spencerwi** [comment]
This seem like a decent .gitignore?

https://www.gitignore.io/api/f%23%2Clinux%2Cwindows%2Cmacos%2Cvim%2Cemacs%2Cvisualstudio%2Cvisualstudiocode

**Comment by cloudRoutine** [comment]
the templates are on https://github.com/fsprojects/Forge/tree/templates
feel free to PR onto them

**Comment by Krzysztof-Cieslak** [comment]
Nah, `.gitignore` goes to root of repo, templates doesn't handle it.

Also we'll need some code to make sure we don't override existing `.gitignore`

**Comment by Krzysztof-Cieslak** [comment]
And yes, this `.gitignore` looks good to me.

**Comment by spencerwi** [comment]
Cool. Then I'll pick this up. Prolly won't get to it tonight, but I can handle it pretty soon here.

**Comment by spencerwi** [comment]
Moving a brief conversation here that happened in Slack: is it better to have Forge make the opinionated move of creating a `.gitignore`, or to instead point users to something like http://gitignore.io/ ?

**Comment by Krzysztof-Cieslak** [comment]
I'd go with opinionated `.gitignore` but feel free to outvote me

**Comment by Krzysztof-Cieslak** [comment]
Merged and released in `1.0.0-alpha012`
