### ISSUE TITLE
Error when installing Forge with Scoop in Windows 7

### ISSUE THREAD

**Issue by fpawel** [fsprojects/Forge#96]
## Expected Behavior
C:\Users\User>scoop install forge
installing forge (0.7.0)...
ok
## Current Behavior
C:\Users\User>scoop install forge
installing forge (0.7.0)
downloading https://github.com/fsprojects/Forge/releases/download/0.7.0/forge.zip...Invoke-WebRequest : can't cast object's type "System.Management.Automation.PSObject" to type
"System.String".
C:\Users\User\AppData\Local\scoop\apps\scoop\current\lib\install.ps1:114 char:5
+     Invoke-WebRequest -Uri $url -OutFile $to -UserAgent 'Scoop/1.0' -Headers @{" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

## Environment
* scoop is up-to-date.
* F# Compiler, version 14.0.23413.0
* PowerShell version:
PS C:\Users\User> $PSVersionTable.PSVersion

Major  3 Minor  0 Build  -1 Revision -1
* Windows 7

**Comment by andredublin** [comment]
Unable to replicate this error on win 10, this sounds more like a scoop issue that a forge issue.
